### ISSUE TITLE
修改配置文件后写回源文件能否支持原格式？

### ISSUE THREAD

**Issue by znoodl** [Unknwon/goconfig#33]
你好，
在配置文件操作中读配置文件和修改配置文件操作居多，单纯的增加配置项较少，而在使用goconfig修改配置文件并写回到源文件后格式被打乱，例如key与key之间的空行被删除，如果有注释可读性会变差。

请问能否支持在修改配置后不打乱源文件格式写回？
谢谢。

**Comment by Unknwon** [comment]
不打乱源文件格式？

**Comment by znoodl** [comment]
是的，比如现在的配置文件为
```
################# aaaaaaaaaaaaaaaaaaaaa #################

# bbbbbbabbbbbbbbbbb
ccc=ddd

# eeeeeeeeee
fff=ggg
```
修改fff为hhh后
```
################# aaaaaaaaaaaaaaaaaaaaa #################
# bbbbbbabbbbbbbbbbb
ccc=ddd
# eeeeeeeeee
fff=hhh
```
空行没有了

**Comment by Unknwon** [comment]
额。。既然是用这个库输出，那么肯定是保持这个库标准统一的输出格式，否则很容易出现一些没有必要的 bug。。建议你 fork 了再改改。。README 已经说明这个库已经不会更新新功能了。
