### ISSUE TITLE
MAC 上使用报错

### ISSUE THREAD

**Issue by JockHai** [Unknwon/goconfig#36]
goroutine 7 [running]:
github.com/Unknwon/goconfig.(*ConfigFile).GetValue(0x0, 0x176f3f8, 0x3, 0x1774a65, 0x8, 0x0, 0x0, 0x0, 0x0)
	/Users/linhai/Downloads/MyProject/Golang_work/src/github.com/Unknwon/goconfig/conf.go:164 +0x67
github.com/Unknwon/goconfig.(*ConfigFile).MustValue(0x0, 0x176f3f8, 0x3, 0x1774a65, 0x8, 0xc42003adf0, 0x1, 0x1, 0xc4201e0000, 0x6d)
	/Users/linhai/Downloads/MyProject/Golang_work/src/github.com/Unknwon/goconfig/conf.go:259 +0x57
goodegg-api/commons/log.SetLog()
	/Users/linhai/Downloads/MyProject/Golang_work/src/goodegg-api/commons/log/log.go:14 +0xbe
main.(*program).run(0x1aa7b50)
	/Users/linhai/Downloads/MyProject/Golang_work/src/goodegg-api/service.go:58 +0x3c
created by main.(*program).Start
	/Users/linhai/Downloads/MyProject/Golang_work/src/goodegg-api/service.go:52 +0x3f
exit status 2

**Comment by Unknwon** [comment]
额。。我完全没看出来你的错误消息是什么。。建议更新一下你的 post 再说。。

**Comment by cjphaha** [comment]
我也遇到了一样的错误，在打包成可执行文件之后就出现了这样的情况：
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x1614e5a]

goroutine 1 [running]:
github.com/Unknwon/goconfig.(*ConfigFile).GetValue(0x0, 0x1868d9c, 0x5, 0x186c68a, 0x8, 0x0, 0x0, 0x0, 0x0)
	/Volumes/PERSON/goCode/pkg/mod/github.com/!unknwon/goconfig@v0.0.0-20200908083735-df7de6a44db8/conf.go:164 +0x5a

**Comment by unknwon** [comment]
@cjphaha 目测你的代码多线程读写 c.BlockMode 了
