### ISSUE TITLE
保留引号内关键字两端的空格会引发歧义

### ISSUE THREAD

**Issue by Hu-Jiang** [Unknwon/goconfig#38]
阅读了您的源码，发现关键字如果在引号内，那么其两端的空格是会被保留的，这会导致一个问题。
比如我初次加载并保存下面的文件：

key_supper = hello
""" key_supper""" = world # 注意:这里key本身包含一个空格

程序处理逻辑认为这是两个不同的关键字，保存后会得到：

key_supper = hello
   &nbsp;    key_supper = world # 注意:这里key本身包含一个空格

然后，再次加载处理后的这个文件并保存，程序将关键字两端去空格、覆盖后，会得到

key_supper = world # 注意:这里key本身包含一个空格

最初认为是两个不同的关键字的文件，经过两次加载并保存之后被覆盖成了一个，逻辑上是不一致的。

**Comment by Hu-Jiang** [comment]
还有个问题：
为什么key支持单引号（或 双引号 或 三引号）包围起来
而value只支持单引号（或三引号）包围起来，而不支持双引号包裹
这里有什么特殊的用意吗？

**Comment by Unknwon** [comment]
老哥你分析的。。很有道理啊！那么输出的时候不应该自动剔除 key 两侧的空白符号就可以解决这个一致性的问题了。

>为什么key支持单引号（或 双引号 或 三引号）包围起来
而value只支持单引号（或三引号）包围起来，而不支持双引号包裹

应该可能也许没有吧。。估计是当时最早的时候没有考虑好怎么统一处理这些引号。

**Comment by Hu-Jiang** [comment]
哈哈。是不是很无语我的问题。
我就是读代码的时候喜欢想一些特殊情况，导致发现一些无伤大雅的小问题：-

**Comment by Unknwon** [comment]
其实你可以去 https://github.com/go-ini/ini 这里测一波，这个新库是后来写的比现在这个 goconfig 规范多了。
