### ISSUE TITLE
GetSection返回值并发读写问题

### ISSUE THREAD

**Issue by jiasijia** [unknwon/goconfig#45]
你好，我在使用GetSection的时候，方法内部加了锁，不会出现并发读写问题，
但是返回值是map引用，在外部多线程访问的时候会发生并发读写的问题，这个能在返回的时候返回一个副本吗

conf, _:= cfg.GetSection("QUEUE." + engine)
value, ok := conf["key"]
上面cfg是全局变量，在 第二行就会出现读写问题

**Comment by unknwon** [comment]
新功能是不可能加的啦，可以考虑改用 [gopkg.in/ini.v1](https://github.com/go-ini/ini)，这个库就有获取副本的方法：https://godoc.org/gopkg.in/ini.v1#Section.KeysHash

**Comment by jiasijia** [comment]
> 新功能是不可能加的啦，可以考虑改用 [gopkg.in/ini.v1](https://github.com/go-ini/ini)，这个库就有获取副本的方法：https://godoc.org/gopkg.in/ini.v1#Section.KeysHash

感谢！
