### ISSUE TITLE
建议添加系统环境变量的解析

### ISSUE THREAD

**Issue by yuangu** [unknwon/goconfig#54]
有些配置是写在环境变量的，希望 能加一个系统环境变量的解析。可以使用
os.ExpandEnv()
这个 方法

**Comment by unknwon** [comment]
Hey!

<img width="653" alt="CleanShot 2021-11-27 at 17 01 34@2x" src="https://user-images.githubusercontent.com/2946214/143675098-21a988c3-1d69-4421-8ffd-766a81120d60.png">
